# Author
#   Pedro Silva

FROM resin/raspberry-pi-node:7-slim
MAINTAINER Pedro Silva

# Default port
EXPOSE 3000

# Copy code and update configuration
COPY ws-router /home/ws-router/
WORKDIR /home/ws-router/
RUN npm install
CMD node app.js
